server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      snapshot: false
  server:
    password: "${LAVALINK_PASSWORD}"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      nico: false
      http: false
      local: false

plugins:
  youtube:
    enabled: true
    allowSearch: false
    allowDirectVideoIds: false
    allowDirectPlaylistIds: false
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED
      - TV
    oauth:
      enabled: "${YOUTUBE_OAUTH_ENABLED:false}"
      refreshToken: "${YOUTUBE_OAUTH_REFRESH_TOKEN:}"
      skipInitialization: "${YOUTUBE_OAUTH_SKIP_INITIALIZATION:false}"
